[project]
name = "bbob-2009"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "matplotlib>=3.10.3",
    "pandas>=3.0.0",
    "pandas-stubs~=3.0.0",
    "scipy>=1.17.0",
    "scipy-stubs~=1.17.0",
]
